export const languageOptions = [
  { value: 'en', label: 'English' },
  { value: 'id', label: 'Bahasa Indonesia' },
] as const

export type AppLanguage = (typeof languageOptions)[number]['value']
export type TimeZonePreference = 'system' | string

type PreferenceStorage = Pick<Storage, 'getItem' | 'setItem'>
type LanguageRoot = Pick<HTMLElement, 'lang'>

const languageStorageKey = 'miku-warp.language'
const timeZoneStorageKey = 'miku-warp.time-zone'
const supportedLanguages = new Set<AppLanguage>(
  languageOptions.map((option) => option.value),
)

const fallbackTimeZones = [
  'UTC',
  'Asia/Jakarta',
  'Asia/Makassar',
  'Asia/Jayapura',
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Asia/Seoul',
  'Europe/London',
  'Europe/Berlin',
  'America/New_York',
  'America/Los_Angeles',
]

export const timeZoneOptions = getSupportedTimeZones()

export const messages = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.characters': 'Characters',
    'nav.accounts': 'Accounts',
    'nav.import': 'Import',
    'nav.backup': 'Backup',
    'nav.settings': 'Settings',
    'nav.trash': 'Trash',
    'common.all': 'All',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.delete': 'Delete',
    'common.deleteAll': 'Delete all',
    'common.deletePermanently': 'Delete permanently',
    'common.deleteSelected': 'Delete selected ({count})',
    'common.deleting': 'Deleting',
    'common.import': 'Import',
    'common.importing': 'Importing',
    'common.loading': 'Loading',
    'common.none': 'None',
    'common.open': 'Open',
    'common.page': 'Page {page}/{pages}',
    'common.restore': 'Restore',
    'common.restoring': 'Restoring',
    'common.save': 'Save',
    'common.saving': 'Saving',
    'common.select': 'Select',
    'common.tryAgain': 'Try again',
    'common.working': 'Working',
    'accessibility.closeConfirmation': 'Close confirmation',
    'accessibility.mainNavigation': 'Main navigation',
    'accessibility.selectedAccount': 'Selected account',
    'accessibility.switchActiveUid': 'Switch active UID',
    'accessibility.workspace': 'Workspace',
    'sidebar.activeUid': 'Active UID',
    'accounts.ariaLabel': 'Accounts',
    'accounts.active': 'Active',
    'accounts.chooseAvatar': 'Choose avatar for UID {uid}',
    'accounts.empty.title': 'No accounts yet',
    'accounts.empty.detail': 'Import game history or manual notes to create a UID.',
    'accounts.lastPull': 'Last pull {date}',
    'accounts.lastPullUnavailable': 'Last pull time unavailable',
    'accounts.moveToTrash': 'Move UID {uid} to Trash',
    'accounts.moveToTrashTitle': 'Move account to Trash',
    'accounts.noSavedPulls': 'No saved pulls',
    'accounts.asiaServer': 'Asia server',
    'accounts.pull': '{count} pull',
    'accounts.pulls': '{count} pulls',
    'avatar.choose': 'Choose avatar',
    'avatar.closePicker': 'Close avatar picker',
    'avatar.empty.detail': 'Run the StarRailRes asset sync to load avatar icons.',
    'avatar.empty.title': 'No avatars synced',
    'avatar.error': 'Avatar update failed',
    'avatar.useDefault': 'Use default',
    'dashboard.setupAria': 'Dashboard setup',
    'dashboard.startHere': 'Start here',
    'dashboard.checkingTitle': 'Checking warp history',
    'dashboard.emptyTitle': 'No warp history yet',
    'dashboard.checkingDetail': 'Miku Warp is checking saved pulls for this account.',
    'dashboard.emptyDetail': 'Import your game history first. After pulls are saved, this dashboard will show banner progress, pity, rate-up stats, and recent results.',
    'dashboard.checkingAction': 'Checking history',
    'dashboard.importAction': 'Import history',
    'banner.allAria': 'All banners: {pulls}',
    'banner.progress': 'Banner progress',
    'banner.summaryAria': 'Banner summary',
    'banner.tabsAria': 'Warp banners',
    'banner.departure': 'Beginner (Departure)',
    'banner.standard': 'Standard',
    'banner.characterEvent': 'Character Event',
    'banner.lightConeEvent': 'Light Cone Event',
    'banner.collabCharacter': 'Collab Character',
    'banner.collabLightCone': 'Collab Light Cone',
    'pity.overviewAria': 'Pity overview',
    'pity.stellarJadeAria': 'Stellar Jade overview',
    'pity.stellarJadeSpent': 'Stellar Jade spent',
    'pity.pullCalculation': '{count} pulls × 160',
    'pity.fiveStar': '5★ pity',
    'pity.fourStar': '4★ pity',
    'pity.last': 'Last:',
    'stats.ariaLabel': 'Banner statistics',
    'stats.averagePity': 'Average pity',
    'stats.totalFiveStar': 'Total 5-star obtained:',
    'stats.nextRateUp': 'Next 5-star rate-up',
    'stats.unknown': 'Unknown',
    'stats.winRate': 'Rate-up win rate',
    'stats.noResult': 'No recorded rate-up result yet',
    'stats.win': '{count} Win',
    'stats.wins': '{count} Wins',
    'stats.loss': '{count} Loss',
    'stats.losses': '{count} Losses',
    'stats.lossLower': '{count} loss',
    'stats.lossesLower': '{count} losses',
    'stats.lossBreakdownAria': '{losses}. Show loss breakdown',
    'stats.standardCharacter': '{count} Standard character',
    'stats.standardCharacters': '{count} Standard characters',
    'stats.standardCharacterLabel': 'Standard character',
    'stats.standardCharactersLabel': 'Standard characters',
    'stats.celestialCharacter': '{count} Celestial Invitation character',
    'stats.celestialCharacters': '{count} Celestial Invitation characters',
    'stats.celestialCharacterLabel': 'Celestial Invitation character',
    'stats.celestialCharactersLabel': 'Celestial Invitation characters',
    'stats.pinHint': 'Click Losses to keep this open',
    'stats.celestialAfter': 'Celestial Invitation result after',
    'stats.celestialUnknown': 'Celestial Invitation prevents an exact rate-up prediction',
    'stats.guaranteedAfter': 'Guaranteed after',
    'stats.guaranteedOffRate': 'Guaranteed after an off-rate 5-star',
    'stats.baseAfter': 'Base chance after',
    'stats.baseBeforeFirst': 'Base chance before the first recorded 5-star',
    'results.ariaLabel': 'Warp result gallery',
    'results.title': 'Warp results',
    'results.rarityFilter': 'Result rarity filter',
    'results.loadingMore': 'Loading more results',
    'results.retryAria': 'Try loading results again',
    'results.showMoreAria': 'Show more results',
    'results.loading': 'Loading results',
    'results.loadFailed': 'Could not load warp results',
    'results.empty': 'No {rarity}-star results for this banner',
    'results.showMore': 'Show more',
    'results.obtainedAtPity': '{item}, obtained at pity {pity}',
    'results.pityTitle': '{item} - Pity {pity}',
    'history.ariaLabel': 'Warp history',
    'history.title': 'Warp history',
    'history.searchAria': 'Search warp item',
    'history.searchPlaceholder': 'Search item',
    'history.rarityFilter': 'Rarity filter',
    'history.emptyFiltered': 'No matching pulls',
    'history.empty': 'No game history imported yet',
    'history.adjustFilters': 'Adjust search or rarity filters.',
    'history.pagination': 'History pagination',
    'history.previousPage': 'Previous history page',
    'history.nextPage': 'Next history page',
    'history.selectItem': 'Select {item}',
    'history.itemType.character': 'Character',
    'history.itemType.lightCone': 'Light Cone',
    'history.pity': 'Pity {value}',
    'import.sourcesAria': 'Import sources',
    'import.records': 'Warp records',
    'import.close': 'Close import',
    'import.gameFolder': 'Game folder',
    'import.scan': 'Scan',
    'import.scanning': 'Scanning',
    'import.opening': 'Opening',
    'import.browse': 'Browse',
    'import.folderHint': 'Choose the folder containing StarRail_Data.',
    'import.detectedFolders': 'Detected game folders',
    'import.folderFailed': 'Folder selection failed',
    'import.scanRecords': 'Scan warp records',
    'import.gameSource': 'Game source',
    'import.gameImport': 'Game import',
    'import.gameImportFailed': 'Game import failed',
    'import.gameImportSaved': 'Game import saved',
    'import.or': 'Or',
    'import.manual': 'Manual import',
    'import.scanningCache': 'Scanning local cache',
    'import.scanInstructionBefore': 'Open',
    'import.gameMenuPath': 'Warp -> View Details -> Records',
    'import.scanInstructionMiddle': 'in Honkai: Star Rail, then press the',
    'import.scanInstructionButton': 'Scan',
    'import.scanInstructionEnd': 'button on the right ->',
    'import.scanFound': 'History source found. Press Import below to fetch warp records.',
    'import.scanNeedsHistory': 'Cache found, but no warp history URL yet. Open Warp History in game, then scan again.',
    'import.scanNotFound': 'Game cache was not found. Choose the game folder that contains StarRail_Data.',
    'import.notScanned': 'Not scanned',
    'import.cacheFilesChecked': '{count} cache files checked',
    'import.candidateRoots': '{count} candidate roots',
    'import.found': 'Found',
    'import.openHistory': 'Open history',
    'import.notFound': 'Not found',
    'import.fetching': 'Fetching game history',
    'import.notImported': 'Not imported',
    'import.meta': '{inserted} new, {restored} restored, {duplicates} duplicates',
    'import.detail': '{inserted} inserted, {restored} restored, {skipped} skipped, {duplicates} duplicates.',
    'import.manualMoved': '{count} manual records moved to UID {uid}.',
    'import.manualMatched': '{count} manual records matched with game history.',
    'import.pagesFetched': '{count} pages fetched for UID {uid}.',
    'import.endpoint': 'Endpoint: {host}',
    'manual.title': 'Warp note',
    'manual.methodAria': 'Manual import method',
    'manual.text': 'Text',
    'manual.selector': 'Item selector',
    'manual.noteInputAria': 'Manual note input',
    'manual.note': 'Note',
    'manual.sample': 'Sample',
    'manual.clear': 'Clear',
    'manual.previewAria': 'Manual import preview',
    'manual.importToUid': 'Import to UID',
    'manual.willBeAdded': '{pulls} will be added to this UID.',
    'manual.previewCategories': 'Preview categories',
    'manual.rarityFilters': 'Rarity filters',
    'manual.issuesAria': 'Manual import issues',
    'manual.line': 'Line {line}',
    'manual.rowsAria': 'Recognized pull rows',
    'manual.noRows': 'No rows',
    'manual.unassigned': 'Unassigned',
    'manual.unknown': 'Unknown',
    'manual.catalog': 'Catalog',
    'manual.catalogLabel': '{version} catalog',
    'manual.range': '{first}-{last} of {total}',
    'manual.pagination': 'Preview pagination',
    'manual.previousPage': 'Previous preview page',
    'manual.nextPage': 'Next preview page',
    'manual.closeMessage': 'Close save message',
    'manual.currentAccount': 'current account',
    'manual.issue.timeWithoutDate': 'Time appears without a date.',
    'manual.issue.unknownSection': 'Section heading is not mapped to a banner type.',
    'manual.issue.beforeTimestamp': 'Item appears before the first timestamp.',
    'manual.issue.missingCatalog': 'Item is not available in the local catalog yet.',
    'manual.issue.empty': 'Manual note is empty.',
    'selector.ariaLabel': 'Manual item selector',
    'selector.selectedPulls': 'Selected pulls',
    'selector.selectedHint': 'Add a result, then click it to edit its details.',
    'selector.addItem': 'Add item',
    'selector.galleryAria': 'Selected warp results',
    'selector.editAria': 'Edit {item}, pity {pity}',
    'selector.emptyTitle': 'No selected pulls',
    'selector.emptyDetail': 'Press Add item to build this manual import.',
    'selector.chooseItem': 'Choose an item',
    'selector.close': 'Close item selector',
    'selector.search': 'Search item',
    'selector.typeFilter': 'Item type filter',
    'selector.characters': 'Characters',
    'selector.lightCones': 'Light Cones',
    'selector.catalogAria': 'Warp item catalog',
    'selector.addAria': 'Add {item}',
    'selector.selectedPull': 'Selected pull',
    'selector.editResult': 'Edit result',
    'selector.closeEditor': 'Close result editor',
    'selector.chooseAnother': 'Click to choose another item',
    'selector.banner': 'Banner',
    'selector.dateTime': 'Date and time',
    'selector.pity': 'Pity',
    'selector.allowedRange': 'Allowed range: 1-{max}',
    'selector.pityVisibility': 'Pity is displayed only for 4-star and 5-star results.',
    'selector.remove': 'Remove',
    'selector.saveChanges': 'Save changes',
    'backup.ariaLabel': 'Backup',
    'backup.backingUp': 'Backing up',
    'backup.backUpNow': 'Back up now',
    'backup.removingCredentials': 'Removing credentials',
    'backup.changeCredentials': 'Change credentials',
    'backup.auto': 'Auto backup',
    'backup.autoAria': 'Auto backup to Google Drive',
    'backup.policyEveryChange': 'On every change',
    'backup.policyDrivePending': 'Drive pending',
    'backup.policyLocalOnly': 'Local autosave only',
    'backup.policyLocalOn': 'Local autosave on',
    'backup.cloudAria': 'Cloud backups',
    'backup.snapshotAt': 'Backup {date}',
    'backup.timeUnavailable': 'Time unavailable',
    'backup.cloudEmpty': 'No cloud autosave yet',
    'backup.cloudEmptyDetail': 'It will upload after the next saved change',
    'backup.local': 'Local backup',
    'backup.recentAria': 'Recent backups',
    'backup.oauthSetup': 'Secure OAuth setup',
    'backup.clientId': 'Desktop Client ID',
    'backup.clientSecret': 'Desktop Client Secret (optional)',
    'backup.clientSecretPlaceholder': 'Enter the client secret when Google provides one',
    'backup.connecting': 'Connecting',
    'backup.saveConnect': 'Save & connect',
    'backup.cancelling': 'Cancelling',
    'backup.disconnecting': 'Disconnecting',
    'backup.disconnect': 'Disconnect',
    'backup.retry': 'Retry',
    'backup.relogin': 'Re-login',
    'backup.connect': 'Connect',
    'backup.sizeUnavailable': 'Size unavailable',
    'backup.status.notConfigured': 'Drive backup unavailable',
    'backup.status.storageUnavailable': 'Secure storage unavailable',
    'backup.status.disconnected': 'Not connected',
    'backup.status.connecting': 'Waiting for Google login',
    'backup.status.failed': 'Connection failed',
    'backup.status.connected': 'Connected',
    'backup.status.needsReauth': 'Needs re-login',
    'backup.detail.notConfigured': 'Enter Desktop OAuth credentials to connect Google Drive securely.',
    'backup.detail.connecting': 'Finish Google login in the browser. Miku Warp will update automatically.',
    'backup.detail.connected': 'Google Drive is connected. Local snapshots can be uploaded to the app data folder.',
    'notice.drivePending': 'Drive autosave pending',
    'notice.autosaveFailed': 'Autosave failed',
    'notice.autoScheduled': '{label} saved. Backup will run automatically.',
    'notice.backupRestored': 'Backup restored',
    'notice.backupReturned': '{file} returned to Local backup.',
    'notice.backupsReturned': '{count} backups returned to Local backup.',
    'notice.chooseUid': 'Choose UID',
    'notice.chooseUidDetail': 'Select the UID that should receive this manual import.',
    'notice.needsReview': 'Needs review',
    'notice.needsReviewDetail': 'Resolve import issues before saving.',
    'notice.saved': 'Saved',
    'notice.saveFailed': 'Save failed',
    'notice.manualSavedDetail': '{inserted} inserted, {restored} restored, {skipped} skipped, {duplicates} duplicates. Catalog {catalog} items.',
    'notice.backupExported': 'Backup exported',
    'notice.exportFailed': 'Export failed',
    'notice.replaceConfirm': 'Import this JSON backup and replace all current local warp history with the file contents?',
    'notice.jsonImported': 'JSON imported',
    'notice.jsonImportFailed': 'JSON import failed',
    'notice.driveConnected': 'Google Drive connected',
    'notice.driveConnectionFailed': 'Google Drive connection failed',
    'notice.driveConnectionIncomplete': 'Google Drive connection incomplete',
    'notice.driveLoginIncomplete': 'Google login did not finish yet. Try Connect again when the browser login is complete.',
    'notice.driveConnectFailed': 'Google Drive connect failed',
    'notice.driveCancelled': 'Google Drive connection cancelled',
    'notice.driveCancelledDetail': 'You can start a new Google Drive connection now.',
    'notice.driveCancelFailed': 'Could not cancel Google Drive connection',
    'notice.autoUnavailable': 'Auto backup unavailable',
    'notice.autoUnavailableDetail': 'Connect Google Drive before enabling automatic backup.',
    'notice.autoUpdated': 'Auto backup updated',
    'notice.autoEnabled': 'Google Drive autosave will run after saved changes.',
    'notice.autoDisabled': 'Google Drive autosave is off. Local autosave stays on.',
    'notice.autoUpdateFailed': 'Auto backup update failed',
    'notice.driveDisconnected': 'Google Drive disconnected',
    'notice.driveDisconnectedDetail': 'Google Drive credentials and the local token were removed from secure storage.',
    'notice.driveDisconnectFailed': 'Google Drive disconnect failed',
    'notice.driveUploadComplete': 'Google Drive upload complete',
    'notice.driveUploadFailed': 'Google Drive upload failed',
    'notice.cloudRestored': 'Cloud backup restored',
    'notice.cloudRestoreFailed': 'Cloud restore failed',
    'notice.restoreFailed': 'Restore failed',
    'notice.backupTrashed': 'Backup moved to Trash',
    'notice.backupTrashedDetail': '{file} moved to Trash. {count} local backups left.',
    'notice.deleteFailed': 'Delete failed',
    'dialog.moveToTrash': 'Move to Trash',
    'dialog.moveAllToTrash': 'Move all to Trash',
    'dialog.moving': 'Moving',
    'dialog.importManualTitle': 'Import manual note?',
    'dialog.moveAccountTitle': 'Move this account to Trash?',
    'dialog.moveAllHistoryTitle': 'Move all history to Trash?',
    'dialog.moveSelectedHistoryTitle': 'Move selected history to Trash?',
    'dialog.restoreBackup': 'Restore backup',
    'dialog.closeApp': 'Close app',
    'dialog.closing': 'Closing',
    'dialog.backupUnfinished': 'Backup is not finished',
    'dialog.manualImportDescription': '{count} detected pulls will be imported into UID {uid}. Existing matching pulls will be skipped as duplicates.',
    'dialog.historySelectedTrash': '{count} selected history items will be moved to Trash for UID {uid}. Their banner pity will be recalculated, and they can be restored for {retention}.',
    'dialog.historyAllTrash': 'All {count} history records for UID {uid} will be moved to Trash. Other UIDs will not be affected, and these items can be restored for {retention}.',
    'dialog.accountTrash': 'UID {uid} and its {pulls} will be moved to Trash. The current active UID will not change, and this account can be restored for {retention}.',
    'dialog.cloudRestoreDescription': 'This Google Drive autosave will be restored into the local database. Existing matching pulls will be skipped as duplicates.',
    'dialog.backupTrashDescription': '{file} ({uids}) will be moved to Trash. Current history will not be changed, and the backup can still be restored from Trash.',
    'dialog.backupRestoreDescription': '{file} contains {uids}. Its history will be merged into the local database, while matching records are skipped.',
    'dialog.backupTrashTitle': 'Move this backup to Trash?',
    'dialog.cloudRestoreTitle': 'Restore cloud backup?',
    'dialog.backupRestoreTitle': 'Restore this backup?',
    'dialog.noUid': 'no identified UID',
    'dialog.multipleUids': 'UIDs {uids}',
    'dialog.restoreSelectedHistoryDescription': '{count} selected history items will return to UID {uid}, and their banner pity will be recalculated.',
    'dialog.restoreHistoryDescription': '{item} will return to UID {uid} history, and its banner pity will be recalculated.',
    'dialog.restoreSelectedHistoryTitle': 'Restore selected history?',
    'dialog.restoreHistoryTitle': 'Restore this history item?',
    'dialog.deleteSelectedHistoryDescription': '{count} selected history items will be permanently deleted from UID {uid}. This action cannot be undone.',
    'dialog.deleteAllHistoryDescription': 'All {count} history items in Trash for UID {uid} will be permanently deleted. This action cannot be undone.',
    'dialog.deleteHistoryDescription': '{item} will be permanently deleted from UID {uid}. This action cannot be undone.',
    'dialog.deleteSelectedTitle': 'Delete selected permanently?',
    'dialog.deleteAllTitle': 'Delete all permanently?',
    'dialog.deleteTitle': 'Delete permanently?',
    'dialog.accountRestoreDescription': 'UID {uid} and its {pulls} will return to Accounts and Dashboard.',
    'dialog.accountDeleteDescription': 'UID {uid} and its {pulls} will be permanently deleted. This action cannot be undone.',
    'dialog.accountRestoreTitle': 'Restore this account?',
    'dialog.accountDeleteTitle': 'Delete this account permanently?',
    'dialog.backupTrashRestore': '{file} will return to Local backup. It can be restored from the Backup page afterward.',
    'dialog.backupTrashDelete': '{file} will be permanently deleted from Trash. This action cannot be undone.',
    'dialog.backupsRestore': '{count} selected backups will return to Local backup. They can be restored from the Backup page afterward.',
    'dialog.backupsDelete': '{count} selected backups will be permanently deleted from Trash. This action cannot be undone.',
    'dialog.backupsDeleteAll': 'All {count} backups in Trash will be permanently deleted. This action cannot be undone.',
    'dialog.backupsRestoreTitle': 'Restore selected backups?',
    'dialog.backupsDeleteTitle': 'Delete selected backups permanently?',
    'dialog.backupsDeleteAllTitle': 'Delete all backups permanently?',
    'dialog.backupDeleteTitle': 'Delete backup permanently?',
    'dialog.closeSaving': 'Miku Warp is still saving the latest backup. Closing now may leave the newest changes waiting for the next app launch.',
    'dialog.closeCloudPending': 'The latest local autosave is ready, but Google Drive backup is still pending. Closing now will keep local data safe and retry cloud backup next time.',
    'dialog.closePending': 'The latest changes have not finished autosaving yet. Closing now may leave them waiting for the next app launch.',
    'detail.backupExport': '{pulls} pulls, {items} catalog items, {batches} import batches.',
    'detail.savedTo': 'Saved to {path}',
    'detail.backupRestore': '{inserted} inserted, {duplicates} skipped as duplicates.',
    'detail.pityRecomputed': '{count} banner pity groups recomputed.',
    'detail.restoredFrom': 'Restored from {path}',
    'detail.jsonPulls': '{count} pulls imported from JSON.',
    'detail.jsonAccounts': '{accounts} accounts and {batches} import batches restored.',
    'detail.jsonReplaced': 'Current local history was replaced from {path}.',
    'detail.cloudUploaded': '{file} uploaded to Google Drive app data.',
    'detail.cloudBytes': '{bytes} bytes uploaded. Remote file id: {id}.',
    'detail.modifiedAt': 'Modified at {date}.',
    'detail.localFile': 'Local file: {path}',
    'error.unexpected': 'Unexpected import error.',
    'desktop.backupBrowsing': 'Backup file browsing',
    'desktop.backupFilter': 'Miku Warp backup JSON',
    'desktop.backupTitle': 'Select Miku Warp backup JSON',
    'desktop.backupFolderTitle': 'Select folder for backup export',
    'desktop.backupSaveTitle': 'Save Miku Warp backup',
    'desktop.folderBrowsing': 'Folder browsing',
    'desktop.folderTitle': 'Select Honkai: Star Rail game folder',
    'desktop.unavailable': 'Browser preview cannot access local files or game folders. Open Miku Warp in the desktop app, then try again.',
    'desktop.actionNeedsApp': '{action} needs the Miku Warp desktop app. {detail}',
    'desktop.thisAction': 'This action',
    'settings.title': 'Settings',
    'settings.theme.title': 'Theme',
    'settings.theme.description': 'Choose how Miku Warp looks on this device.',
    'settings.theme.aria': 'Application theme',
    'settings.theme.system': 'System',
    'settings.theme.systemDetail': 'Follow the operating system appearance.',
    'settings.theme.dark': 'Dark',
    'settings.theme.darkDetail': 'Neutral dark colors for low-light use.',
    'settings.theme.light': 'Light',
    'settings.theme.lightDetail': 'Bright neutral colors with strong contrast.',
    'settings.theme.vampire': 'Vampire',
    'settings.theme.vampireDetail': 'Black-red surfaces with white text and red glow.',
    'settings.theme.cyber': 'Cyber',
    'settings.theme.cyberDetail': 'Midnight blue surfaces with neon cyan accents.',
    'settings.theme.punk': 'Punk',
    'settings.theme.punkDetail': 'High-contrast ink surfaces with hot pink accents.',
    'settings.theme.celestial': 'Celestial',
    'settings.theme.celestialDetail': 'Sacred ivory surfaces with warm gold accents.',
    'settings.language.title': 'Language',
    'settings.language.description': 'Choose the interface language.',
    'settings.timezone.title': 'Timezone',
    'settings.timezone.description':
      'Used for displayed dates and new manual imports.',
    'settings.timezone.system': 'System default',
    'settings.trash.title': 'Trash retention',
    'settings.trash.description':
      'Choose when trashed data is permanently deleted.',
    'settings.trash.warning':
      'Items older than the selected period may be deleted permanently.',
    'settings.trash.updating': 'Updating retention',
    'retention.never': 'Never',
    'retention.30': '30 days',
    'retention.90': '90 days',
    'retention.183': '6 months',
    'retention.365': '1 year',
    'trash.summary': 'Items are removed permanently after {retention}.',
    'trash.summary.never': 'Items stay in Trash until you delete them permanently.',
    'trash.history.empty': 'Deleted warp records will stay here for {retention}.',
    'trash.accounts.empty': 'Deleted accounts will stay here for {retention}.',
    'trash.backups.empty': 'Deleted local backups will stay here for {retention}.',
    'trash.ariaLabel': 'Trash history',
    'trash.categories': 'Trash categories',
    'trash.deletedHistory': 'Deleted history',
    'trash.deletedAccounts': 'Deleted accounts',
    'trash.deletedBackups': 'Deleted backups',
    'trash.tabHistory': 'History {count}',
    'trash.tabAccounts': 'Accounts {count}',
    'trash.tabBackups': 'Backups {count}',
    'trash.loading': 'Loading Trash',
    'trash.empty': 'Trash is empty',
    'trash.loadingAccounts': 'Loading account Trash',
    'trash.noAccounts': 'No deleted accounts',
    'trash.loadingBackups': 'Loading backup Trash',
    'trash.noBackups': 'No deleted backups',
    'trash.pagination': 'Trash pagination',
    'trash.previousPage': 'Previous Trash page',
    'trash.nextPage': 'Next Trash page',
    'trash.restoreSelected': 'Restore selected ({count})',
    'trash.warpedAt': 'Warped {date}',
    'trash.deletedAt': 'Deleted {date}',
    'trash.deletingItem': 'Deleting {item}',
    'trash.permanentlyDeleteItem': 'Permanently delete {item}',
    'trash.selectBackup': 'Select {file}',
    'trash.deletingBackup': 'Deleting {file}',
    'trash.permanentlyDeleteBackup': 'Permanently delete {file}',
    'trash.deletingAccount': 'Deleting UID {uid}',
    'trash.permanentlyDeleteAccount': 'Permanently delete UID {uid}',
    'roster.title': 'Character Roster',
    'roster.reimport': 'Import again',
    'roster.import': 'Import',
    'roster.importing': 'Importing…',
    'roster.loading': 'Loading characters',
    'roster.howToTitle': 'How to get the data',
    'roster.howToStep1': 'Open HoYoLAB and go to Battle Chronicle for Honkai: Star Rail.',
    'roster.howToStep2': 'Open DevTools (F12) and switch to the Network tab.',
    'roster.howToStep3': 'Type "avatar" in the filter box and select Fetch/XHR.',
    'roster.howToStep4': 'Right-click the "avatar/info" request, choose Copy > Copy response.',
    'roster.howToStep5': 'Paste the copied JSON below, then click Import.',
    'roster.pastePlaceholder': 'Paste the JSON response here…',
    'roster.level': 'Lv.',
    'roster.eidolon': 'Eidolon',
    'roster.lightCone': 'Light Cone',
    'roster.superimpose': 'S{value}',
    'roster.superimposeFull': 'Superimpose',
    'roster.noLightCone': 'No Light Cone',
    'roster.searchPlaceholder': 'Search characters…',
    'roster.noMatches': 'No matching characters',
  },
  id: {
    'nav.dashboard': 'Dasbor',
    'nav.characters': 'Karakter',
    'nav.accounts': 'Akun',
    'nav.import': 'Impor',
    'nav.backup': 'Cadangan',
    'nav.settings': 'Pengaturan',
    'nav.trash': 'Sampah',
    'common.all': 'Semua',
    'common.cancel': 'Batal',
    'common.close': 'Tutup',
    'common.delete': 'Hapus',
    'common.deleteAll': 'Hapus semua',
    'common.deletePermanently': 'Hapus permanen',
    'common.deleteSelected': 'Hapus yang dipilih ({count})',
    'common.deleting': 'Menghapus',
    'common.import': 'Impor',
    'common.importing': 'Mengimpor',
    'common.loading': 'Memuat',
    'common.none': 'Tidak ada',
    'common.open': 'Buka',
    'common.page': 'Halaman {page}/{pages}',
    'common.restore': 'Pulihkan',
    'common.restoring': 'Memulihkan',
    'common.save': 'Simpan',
    'common.saving': 'Menyimpan',
    'common.select': 'Pilih',
    'common.tryAgain': 'Coba lagi',
    'common.working': 'Memproses',
    'accessibility.closeConfirmation': 'Tutup konfirmasi',
    'accessibility.mainNavigation': 'Navigasi utama',
    'accessibility.selectedAccount': 'Akun terpilih',
    'accessibility.switchActiveUid': 'Ganti UID aktif',
    'accessibility.workspace': 'Ruang kerja',
    'sidebar.activeUid': 'UID Aktif',
    'accounts.ariaLabel': 'Akun',
    'accounts.active': 'Aktif',
    'accounts.chooseAvatar': 'Pilih avatar untuk UID {uid}',
    'accounts.empty.title': 'Belum ada akun',
    'accounts.empty.detail': 'Impor riwayat game atau catatan manual untuk membuat UID.',
    'accounts.lastPull': 'Warp terakhir {date}',
    'accounts.lastPullUnavailable': 'Waktu warp terakhir tidak tersedia',
    'accounts.moveToTrash': 'Pindahkan UID {uid} ke Sampah',
    'accounts.moveToTrashTitle': 'Pindahkan akun ke Sampah',
    'accounts.noSavedPulls': 'Belum ada warp tersimpan',
    'accounts.asiaServer': 'Server Asia',
    'accounts.pull': '{count} warp',
    'accounts.pulls': '{count} warp',
    'avatar.choose': 'Pilih avatar',
    'avatar.closePicker': 'Tutup pemilih avatar',
    'avatar.empty.detail': 'Jalankan sinkronisasi aset StarRailRes untuk memuat ikon avatar.',
    'avatar.empty.title': 'Belum ada avatar tersinkronisasi',
    'avatar.error': 'Gagal memperbarui avatar',
    'avatar.useDefault': 'Gunakan bawaan',
    'dashboard.setupAria': 'Penyiapan dasbor',
    'dashboard.startHere': 'Mulai di sini',
    'dashboard.checkingTitle': 'Memeriksa riwayat warp',
    'dashboard.emptyTitle': 'Belum ada riwayat warp',
    'dashboard.checkingDetail': 'Miku Warp sedang memeriksa warp tersimpan untuk akun ini.',
    'dashboard.emptyDetail': 'Impor riwayat game terlebih dahulu. Setelah warp tersimpan, dasbor ini akan menampilkan progres banner, pity, statistik rate-up, dan hasil terbaru.',
    'dashboard.checkingAction': 'Memeriksa riwayat',
    'dashboard.importAction': 'Impor riwayat',
    'banner.allAria': 'Semua banner: {pulls}',
    'banner.progress': 'Progres banner',
    'banner.summaryAria': 'Ringkasan banner',
    'banner.tabsAria': 'Banner warp',
    'banner.departure': 'Pemula (Departure)',
    'banner.standard': 'Standar',
    'banner.characterEvent': 'Event Karakter',
    'banner.lightConeEvent': 'Event Light Cone',
    'banner.collabCharacter': 'Karakter Kolaborasi',
    'banner.collabLightCone': 'Light Cone Kolaborasi',
    'pity.overviewAria': 'Ringkasan pity',
    'pity.stellarJadeAria': 'Ringkasan Stellar Jade',
    'pity.stellarJadeSpent': 'Stellar Jade terpakai',
    'pity.pullCalculation': '{count} warp × 160',
    'pity.fiveStar': 'Pity 5★',
    'pity.fourStar': 'Pity 4★',
    'pity.last': 'Terakhir:',
    'stats.ariaLabel': 'Statistik banner',
    'stats.averagePity': 'Rata-rata pity',
    'stats.totalFiveStar': 'Total 5 bintang diperoleh:',
    'stats.nextRateUp': 'Rate-up 5 bintang berikutnya',
    'stats.unknown': 'Belum diketahui',
    'stats.winRate': 'Tingkat kemenangan rate-up',
    'stats.noResult': 'Belum ada hasil rate-up tercatat',
    'stats.win': '{count} Menang',
    'stats.wins': '{count} Menang',
    'stats.loss': '{count} Kalah',
    'stats.losses': '{count} Kalah',
    'stats.lossLower': '{count} kalah',
    'stats.lossesLower': '{count} kalah',
    'stats.lossBreakdownAria': '{losses}. Tampilkan rincian kekalahan',
    'stats.standardCharacter': '{count} karakter Standar',
    'stats.standardCharacters': '{count} karakter Standar',
    'stats.standardCharacterLabel': 'karakter Standar',
    'stats.standardCharactersLabel': 'karakter Standar',
    'stats.celestialCharacter': '{count} karakter Celestial Invitation',
    'stats.celestialCharacters': '{count} karakter Celestial Invitation',
    'stats.celestialCharacterLabel': 'karakter Celestial Invitation',
    'stats.celestialCharactersLabel': 'karakter Celestial Invitation',
    'stats.pinHint': 'Klik Kalah agar rincian tetap terbuka',
    'stats.celestialAfter': 'Hasil Celestial Invitation setelah',
    'stats.celestialUnknown': 'Celestial Invitation membuat prediksi rate-up pasti tidak tersedia',
    'stats.guaranteedAfter': 'Dijamin setelah',
    'stats.guaranteedOffRate': 'Dijamin setelah mendapat 5 bintang non-rate-up',
    'stats.baseAfter': 'Peluang dasar setelah',
    'stats.baseBeforeFirst': 'Peluang dasar sebelum 5 bintang pertama yang tercatat',
    'results.ariaLabel': 'Galeri hasil warp',
    'results.title': 'Hasil warp',
    'results.rarityFilter': 'Filter rarity hasil',
    'results.loadingMore': 'Memuat lebih banyak hasil',
    'results.retryAria': 'Coba muat hasil lagi',
    'results.showMoreAria': 'Tampilkan lebih banyak hasil',
    'results.loading': 'Memuat hasil',
    'results.loadFailed': 'Tidak dapat memuat hasil warp',
    'results.empty': 'Tidak ada hasil {rarity} bintang untuk banner ini',
    'results.showMore': 'Tampilkan lainnya',
    'results.obtainedAtPity': '{item}, diperoleh pada pity {pity}',
    'results.pityTitle': '{item} - Pity {pity}',
    'history.ariaLabel': 'Riwayat warp',
    'history.title': 'Riwayat warp',
    'history.searchAria': 'Cari item warp',
    'history.searchPlaceholder': 'Cari item',
    'history.rarityFilter': 'Filter rarity',
    'history.emptyFiltered': 'Tidak ada warp yang cocok',
    'history.empty': 'Belum ada riwayat game yang diimpor',
    'history.adjustFilters': 'Sesuaikan pencarian atau filter rarity.',
    'history.pagination': 'Navigasi halaman riwayat',
    'history.previousPage': 'Halaman riwayat sebelumnya',
    'history.nextPage': 'Halaman riwayat berikutnya',
    'history.selectItem': 'Pilih {item}',
    'history.itemType.character': 'Karakter',
    'history.itemType.lightCone': 'Light Cone',
    'history.pity': 'Pity {value}',
    'import.sourcesAria': 'Sumber impor',
    'import.records': 'Riwayat warp',
    'import.close': 'Tutup impor',
    'import.gameFolder': 'Folder game',
    'import.scan': 'Pindai',
    'import.scanning': 'Memindai',
    'import.opening': 'Membuka',
    'import.browse': 'Telusuri',
    'import.folderHint': 'Pilih folder yang berisi StarRail_Data.',
    'import.detectedFolders': 'Folder game yang terdeteksi',
    'import.folderFailed': 'Gagal memilih folder',
    'import.scanRecords': 'Pindai riwayat warp',
    'import.gameSource': 'Sumber game',
    'import.gameImport': 'Impor game',
    'import.gameImportFailed': 'Impor game gagal',
    'import.gameImportSaved': 'Impor game tersimpan',
    'import.or': 'Atau',
    'import.manual': 'Impor manual',
    'import.scanningCache': 'Memindai cache lokal',
    'import.scanInstructionBefore': 'Buka',
    'import.gameMenuPath': 'Warp -> Lihat Detail -> Catatan',
    'import.scanInstructionMiddle': 'di Honkai: Star Rail, lalu tekan tombol',
    'import.scanInstructionButton': 'Pindai',
    'import.scanInstructionEnd': 'di sebelah kanan ->',
    'import.scanFound': 'Sumber riwayat ditemukan. Tekan Impor di bawah untuk mengambil riwayat warp.',
    'import.scanNeedsHistory': 'Cache ditemukan, tetapi URL riwayat warp belum ada. Buka Riwayat Warp di game, lalu pindai lagi.',
    'import.scanNotFound': 'Cache game tidak ditemukan. Pilih folder game yang berisi StarRail_Data.',
    'import.notScanned': 'Belum dipindai',
    'import.cacheFilesChecked': '{count} file cache diperiksa',
    'import.candidateRoots': '{count} lokasi kandidat',
    'import.found': 'Ditemukan',
    'import.openHistory': 'Buka riwayat',
    'import.notFound': 'Tidak ditemukan',
    'import.fetching': 'Mengambil riwayat game',
    'import.notImported': 'Belum diimpor',
    'import.meta': '{inserted} baru, {restored} dipulihkan, {duplicates} duplikat',
    'import.detail': '{inserted} ditambahkan, {restored} dipulihkan, {skipped} dilewati, {duplicates} duplikat.',
    'import.manualMoved': '{count} riwayat manual dipindahkan ke UID {uid}.',
    'import.manualMatched': '{count} riwayat manual dicocokkan dengan riwayat game.',
    'import.pagesFetched': '{count} halaman diambil untuk UID {uid}.',
    'import.endpoint': 'Endpoint: {host}',
    'manual.title': 'Catatan warp',
    'manual.methodAria': 'Metode impor manual',
    'manual.text': 'Teks',
    'manual.selector': 'Pemilih item',
    'manual.noteInputAria': 'Input catatan manual',
    'manual.note': 'Catatan',
    'manual.sample': 'Contoh',
    'manual.clear': 'Bersihkan',
    'manual.previewAria': 'Pratinjau impor manual',
    'manual.importToUid': 'Impor ke UID',
    'manual.willBeAdded': '{pulls} akan ditambahkan ke UID ini.',
    'manual.previewCategories': 'Kategori pratinjau',
    'manual.rarityFilters': 'Filter rarity',
    'manual.issuesAria': 'Masalah impor manual',
    'manual.line': 'Baris {line}',
    'manual.rowsAria': 'Baris warp yang dikenali',
    'manual.noRows': 'Tidak ada baris',
    'manual.unassigned': 'Belum ditentukan',
    'manual.unknown': 'Tidak diketahui',
    'manual.catalog': 'Katalog',
    'manual.catalogLabel': 'Katalog {version}',
    'manual.range': '{first}-{last} dari {total}',
    'manual.pagination': 'Navigasi halaman pratinjau',
    'manual.previousPage': 'Halaman pratinjau sebelumnya',
    'manual.nextPage': 'Halaman pratinjau berikutnya',
    'manual.closeMessage': 'Tutup pesan penyimpanan',
    'manual.currentAccount': 'akun saat ini',
    'manual.issue.timeWithoutDate': 'Waktu ditulis tanpa tanggal.',
    'manual.issue.unknownSection': 'Judul bagian belum dipetakan ke jenis banner.',
    'manual.issue.beforeTimestamp': 'Item ditulis sebelum timestamp pertama.',
    'manual.issue.missingCatalog': 'Item belum tersedia di katalog lokal.',
    'manual.issue.empty': 'Catatan manual kosong.',
    'selector.ariaLabel': 'Pemilih item manual',
    'selector.selectedPulls': 'Warp yang dipilih',
    'selector.selectedHint': 'Tambahkan hasil, lalu klik untuk mengubah detailnya.',
    'selector.addItem': 'Tambah item',
    'selector.galleryAria': 'Hasil warp yang dipilih',
    'selector.editAria': 'Ubah {item}, pity {pity}',
    'selector.emptyTitle': 'Belum ada warp yang dipilih',
    'selector.emptyDetail': 'Tekan Tambah item untuk menyusun impor manual ini.',
    'selector.chooseItem': 'Pilih item',
    'selector.close': 'Tutup pemilih item',
    'selector.search': 'Cari item',
    'selector.typeFilter': 'Filter jenis item',
    'selector.characters': 'Karakter',
    'selector.lightCones': 'Light Cone',
    'selector.catalogAria': 'Katalog item warp',
    'selector.addAria': 'Tambahkan {item}',
    'selector.selectedPull': 'Warp terpilih',
    'selector.editResult': 'Ubah hasil',
    'selector.closeEditor': 'Tutup editor hasil',
    'selector.chooseAnother': 'Klik untuk memilih item lain',
    'selector.banner': 'Banner',
    'selector.dateTime': 'Tanggal dan waktu',
    'selector.pity': 'Pity',
    'selector.allowedRange': 'Rentang yang diizinkan: 1-{max}',
    'selector.pityVisibility': 'Pity hanya ditampilkan untuk hasil 4 bintang dan 5 bintang.',
    'selector.remove': 'Hapus',
    'selector.saveChanges': 'Simpan perubahan',
    'backup.ariaLabel': 'Cadangan',
    'backup.backingUp': 'Mencadangkan',
    'backup.backUpNow': 'Cadangkan sekarang',
    'backup.removingCredentials': 'Menghapus kredensial',
    'backup.changeCredentials': 'Ganti kredensial',
    'backup.auto': 'Cadangan otomatis',
    'backup.autoAria': 'Cadangan otomatis ke Google Drive',
    'backup.policyEveryChange': 'Pada setiap perubahan',
    'backup.policyDrivePending': 'Drive tertunda',
    'backup.policyLocalOnly': 'Hanya autosave lokal',
    'backup.policyLocalOn': 'Autosave lokal aktif',
    'backup.cloudAria': 'Cadangan cloud',
    'backup.snapshotAt': 'Cadangan {date}',
    'backup.timeUnavailable': 'Waktu tidak tersedia',
    'backup.cloudEmpty': 'Belum ada autosave cloud',
    'backup.cloudEmptyDetail': 'Akan diunggah setelah perubahan tersimpan berikutnya',
    'backup.local': 'Cadangan lokal',
    'backup.recentAria': 'Cadangan terbaru',
    'backup.oauthSetup': 'Penyiapan OAuth aman',
    'backup.clientId': 'Client ID Desktop',
    'backup.clientSecret': 'Client Secret Desktop (opsional)',
    'backup.clientSecretPlaceholder': 'Masukkan client secret jika diberikan oleh Google',
    'backup.connecting': 'Menghubungkan',
    'backup.saveConnect': 'Simpan & hubungkan',
    'backup.cancelling': 'Membatalkan',
    'backup.disconnecting': 'Memutuskan',
    'backup.disconnect': 'Putuskan',
    'backup.retry': 'Coba lagi',
    'backup.relogin': 'Login ulang',
    'backup.connect': 'Hubungkan',
    'backup.sizeUnavailable': 'Ukuran tidak tersedia',
    'backup.status.notConfigured': 'Cadangan Drive tidak tersedia',
    'backup.status.storageUnavailable': 'Penyimpanan aman tidak tersedia',
    'backup.status.disconnected': 'Belum terhubung',
    'backup.status.connecting': 'Menunggu login Google',
    'backup.status.failed': 'Koneksi gagal',
    'backup.status.connected': 'Terhubung',
    'backup.status.needsReauth': 'Perlu login ulang',
    'backup.detail.notConfigured': 'Masukkan kredensial OAuth Desktop untuk menghubungkan Google Drive secara aman.',
    'backup.detail.connecting': 'Selesaikan login Google di browser. Miku Warp akan memperbarui status secara otomatis.',
    'backup.detail.connected': 'Google Drive terhubung. Snapshot lokal dapat diunggah ke folder data aplikasi.',
    'notice.drivePending': 'Autosave Drive tertunda',
    'notice.autosaveFailed': 'Autosave gagal',
    'notice.autoScheduled': '{label} tersimpan. Cadangan akan berjalan otomatis.',
    'notice.backupRestored': 'Cadangan dipulihkan',
    'notice.backupReturned': '{file} dikembalikan ke Cadangan lokal.',
    'notice.backupsReturned': '{count} cadangan dikembalikan ke Cadangan lokal.',
    'notice.chooseUid': 'Pilih UID',
    'notice.chooseUidDetail': 'Pilih UID yang akan menerima impor manual ini.',
    'notice.needsReview': 'Perlu diperiksa',
    'notice.needsReviewDetail': 'Selesaikan masalah impor sebelum menyimpan.',
    'notice.saved': 'Tersimpan',
    'notice.saveFailed': 'Gagal menyimpan',
    'notice.manualSavedDetail': '{inserted} ditambahkan, {restored} dipulihkan, {skipped} dilewati, {duplicates} duplikat. Katalog {catalog} item.',
    'notice.backupExported': 'Cadangan diekspor',
    'notice.exportFailed': 'Ekspor gagal',
    'notice.replaceConfirm': 'Impor cadangan JSON ini dan ganti seluruh riwayat warp lokal saat ini dengan isi file?',
    'notice.jsonImported': 'JSON diimpor',
    'notice.jsonImportFailed': 'Impor JSON gagal',
    'notice.driveConnected': 'Google Drive terhubung',
    'notice.driveConnectionFailed': 'Koneksi Google Drive gagal',
    'notice.driveConnectionIncomplete': 'Koneksi Google Drive belum selesai',
    'notice.driveLoginIncomplete': 'Login Google belum selesai. Coba Hubungkan lagi setelah login di browser selesai.',
    'notice.driveConnectFailed': 'Gagal menghubungkan Google Drive',
    'notice.driveCancelled': 'Koneksi Google Drive dibatalkan',
    'notice.driveCancelledDetail': 'Kamu sekarang dapat memulai koneksi Google Drive baru.',
    'notice.driveCancelFailed': 'Tidak dapat membatalkan koneksi Google Drive',
    'notice.autoUnavailable': 'Cadangan otomatis tidak tersedia',
    'notice.autoUnavailableDetail': 'Hubungkan Google Drive sebelum mengaktifkan cadangan otomatis.',
    'notice.autoUpdated': 'Cadangan otomatis diperbarui',
    'notice.autoEnabled': 'Autosave Google Drive akan berjalan setelah perubahan tersimpan.',
    'notice.autoDisabled': 'Autosave Google Drive nonaktif. Autosave lokal tetap aktif.',
    'notice.autoUpdateFailed': 'Gagal memperbarui cadangan otomatis',
    'notice.driveDisconnected': 'Google Drive terputus',
    'notice.driveDisconnectedDetail': 'Kredensial Google Drive dan token lokal telah dihapus dari penyimpanan aman.',
    'notice.driveDisconnectFailed': 'Gagal memutus Google Drive',
    'notice.driveUploadComplete': 'Unggahan Google Drive selesai',
    'notice.driveUploadFailed': 'Unggahan Google Drive gagal',
    'notice.cloudRestored': 'Cadangan cloud dipulihkan',
    'notice.cloudRestoreFailed': 'Pemulihan cloud gagal',
    'notice.restoreFailed': 'Pemulihan gagal',
    'notice.backupTrashed': 'Cadangan dipindahkan ke Sampah',
    'notice.backupTrashedDetail': '{file} dipindahkan ke Sampah. Tersisa {count} cadangan lokal.',
    'notice.deleteFailed': 'Penghapusan gagal',
    'dialog.moveToTrash': 'Pindahkan ke Sampah',
    'dialog.moveAllToTrash': 'Pindahkan semua ke Sampah',
    'dialog.moving': 'Memindahkan',
    'dialog.importManualTitle': 'Impor catatan manual?',
    'dialog.moveAccountTitle': 'Pindahkan akun ini ke Sampah?',
    'dialog.moveAllHistoryTitle': 'Pindahkan seluruh riwayat ke Sampah?',
    'dialog.moveSelectedHistoryTitle': 'Pindahkan riwayat terpilih ke Sampah?',
    'dialog.restoreBackup': 'Pulihkan cadangan',
    'dialog.closeApp': 'Tutup aplikasi',
    'dialog.closing': 'Menutup',
    'dialog.backupUnfinished': 'Cadangan belum selesai',
    'dialog.manualImportDescription': '{count} warp terdeteksi akan diimpor ke UID {uid}. Warp yang cocok akan dilewati sebagai duplikat.',
    'dialog.historySelectedTrash': '{count} riwayat terpilih akan dipindahkan ke Sampah untuk UID {uid}. Pity banner akan dihitung ulang dan dapat dipulihkan selama {retention}.',
    'dialog.historyAllTrash': 'Seluruh {count} riwayat untuk UID {uid} akan dipindahkan ke Sampah. UID lain tidak terpengaruh dan item dapat dipulihkan selama {retention}.',
    'dialog.accountTrash': 'UID {uid} beserta {pulls} akan dipindahkan ke Sampah. UID aktif tidak berubah dan akun ini dapat dipulihkan selama {retention}.',
    'dialog.cloudRestoreDescription': 'Autosave Google Drive ini akan dipulihkan ke database lokal. Warp yang cocok akan dilewati sebagai duplikat.',
    'dialog.backupTrashDescription': '{file} ({uids}) akan dipindahkan ke Sampah. Riwayat saat ini tidak berubah dan cadangan masih dapat dipulihkan dari Sampah.',
    'dialog.backupRestoreDescription': '{file} berisi {uids}. Riwayatnya akan digabungkan ke database lokal, sementara data yang cocok dilewati.',
    'dialog.backupTrashTitle': 'Pindahkan cadangan ini ke Sampah?',
    'dialog.cloudRestoreTitle': 'Pulihkan cadangan cloud?',
    'dialog.backupRestoreTitle': 'Pulihkan cadangan ini?',
    'dialog.noUid': 'tidak ada UID teridentifikasi',
    'dialog.multipleUids': 'UID {uids}',
    'dialog.restoreSelectedHistoryDescription': '{count} riwayat terpilih akan dikembalikan ke UID {uid} dan pity banner dihitung ulang.',
    'dialog.restoreHistoryDescription': '{item} akan dikembalikan ke riwayat UID {uid} dan pity banner dihitung ulang.',
    'dialog.restoreSelectedHistoryTitle': 'Pulihkan riwayat terpilih?',
    'dialog.restoreHistoryTitle': 'Pulihkan item riwayat ini?',
    'dialog.deleteSelectedHistoryDescription': '{count} riwayat terpilih akan dihapus permanen dari UID {uid}. Tindakan ini tidak dapat dibatalkan.',
    'dialog.deleteAllHistoryDescription': 'Seluruh {count} riwayat di Sampah untuk UID {uid} akan dihapus permanen. Tindakan ini tidak dapat dibatalkan.',
    'dialog.deleteHistoryDescription': '{item} akan dihapus permanen dari UID {uid}. Tindakan ini tidak dapat dibatalkan.',
    'dialog.deleteSelectedTitle': 'Hapus permanen yang dipilih?',
    'dialog.deleteAllTitle': 'Hapus semua secara permanen?',
    'dialog.deleteTitle': 'Hapus permanen?',
    'dialog.accountRestoreDescription': 'UID {uid} beserta {pulls} akan dikembalikan ke Akun dan Dasbor.',
    'dialog.accountDeleteDescription': 'UID {uid} beserta {pulls} akan dihapus permanen. Tindakan ini tidak dapat dibatalkan.',
    'dialog.accountRestoreTitle': 'Pulihkan akun ini?',
    'dialog.accountDeleteTitle': 'Hapus akun ini secara permanen?',
    'dialog.backupTrashRestore': '{file} akan dikembalikan ke Cadangan lokal dan dapat dipulihkan dari halaman Cadangan.',
    'dialog.backupTrashDelete': '{file} akan dihapus permanen dari Sampah. Tindakan ini tidak dapat dibatalkan.',
    'dialog.backupsRestore': '{count} cadangan terpilih akan dikembalikan ke Cadangan lokal dan dapat dipulihkan dari halaman Cadangan.',
    'dialog.backupsDelete': '{count} cadangan terpilih akan dihapus permanen dari Sampah. Tindakan ini tidak dapat dibatalkan.',
    'dialog.backupsDeleteAll': 'Seluruh {count} cadangan di Sampah akan dihapus permanen. Tindakan ini tidak dapat dibatalkan.',
    'dialog.backupsRestoreTitle': 'Pulihkan cadangan terpilih?',
    'dialog.backupsDeleteTitle': 'Hapus permanen cadangan terpilih?',
    'dialog.backupsDeleteAllTitle': 'Hapus permanen seluruh cadangan?',
    'dialog.backupDeleteTitle': 'Hapus cadangan secara permanen?',
    'dialog.closeSaving': 'Miku Warp masih menyimpan cadangan terbaru. Menutup sekarang dapat membuat perubahan terbaru menunggu hingga aplikasi dibuka lagi.',
    'dialog.closeCloudPending': 'Autosave lokal terbaru sudah siap, tetapi cadangan Google Drive masih tertunda. Data lokal tetap aman dan cadangan cloud akan dicoba lagi nanti.',
    'dialog.closePending': 'Perubahan terbaru belum selesai disimpan otomatis. Menutup sekarang dapat membuatnya menunggu hingga aplikasi dibuka lagi.',
    'detail.backupExport': '{pulls} warp, {items} item katalog, {batches} batch impor.',
    'detail.savedTo': 'Disimpan ke {path}',
    'detail.backupRestore': '{inserted} ditambahkan, {duplicates} dilewati sebagai duplikat.',
    'detail.pityRecomputed': '{count} grup pity banner dihitung ulang.',
    'detail.restoredFrom': 'Dipulihkan dari {path}',
    'detail.jsonPulls': '{count} warp diimpor dari JSON.',
    'detail.jsonAccounts': '{accounts} akun dan {batches} batch impor dipulihkan.',
    'detail.jsonReplaced': 'Riwayat lokal saat ini diganti dari {path}.',
    'detail.cloudUploaded': '{file} diunggah ke data aplikasi Google Drive.',
    'detail.cloudBytes': '{bytes} byte diunggah. ID file remote: {id}.',
    'detail.modifiedAt': 'Diubah pada {date}.',
    'detail.localFile': 'File lokal: {path}',
    'error.unexpected': 'Terjadi kesalahan impor yang tidak terduga.',
    'desktop.backupBrowsing': 'Penelusuran file cadangan',
    'desktop.backupFilter': 'JSON cadangan Miku Warp',
    'desktop.backupTitle': 'Pilih JSON cadangan Miku Warp',
    'desktop.backupFolderTitle': 'Pilih folder untuk ekspor cadangan',
    'desktop.backupSaveTitle': 'Simpan cadangan Miku Warp',
    'desktop.folderBrowsing': 'Penelusuran folder',
    'desktop.folderTitle': 'Pilih folder game Honkai: Star Rail',
    'desktop.unavailable': 'Pratinjau browser tidak dapat mengakses file lokal atau folder game. Buka Miku Warp melalui aplikasi desktop, lalu coba lagi.',
    'desktop.actionNeedsApp': '{action} memerlukan aplikasi desktop Miku Warp. {detail}',
    'desktop.thisAction': 'Tindakan ini',
    'settings.title': 'Pengaturan',
    'settings.theme.title': 'Tema',
    'settings.theme.description': 'Pilih tampilan Miku Warp di perangkat ini.',
    'settings.theme.aria': 'Tema aplikasi',
    'settings.theme.system': 'Sistem',
    'settings.theme.systemDetail': 'Ikuti tampilan sistem operasi.',
    'settings.theme.dark': 'Gelap',
    'settings.theme.darkDetail': 'Warna gelap netral untuk kondisi minim cahaya.',
    'settings.theme.light': 'Terang',
    'settings.theme.lightDetail': 'Warna netral terang dengan kontras kuat.',
    'settings.theme.vampire': 'Vampire',
    'settings.theme.vampireDetail': 'Permukaan hitam-merah dengan teks putih dan glow merah.',
    'settings.theme.cyber': 'Cyber',
    'settings.theme.cyberDetail': 'Permukaan biru malam dengan aksen cyan neon.',
    'settings.theme.punk': 'Punk',
    'settings.theme.punkDetail': 'Permukaan hitam kontras dengan aksen hot pink.',
    'settings.theme.celestial': 'Celestial',
    'settings.theme.celestialDetail': 'Nuansa surgawi putih ivory dengan aksen emas hangat.',
    'settings.language.title': 'Bahasa',
    'settings.language.description': 'Pilih bahasa antarmuka aplikasi.',
    'settings.timezone.title': 'Zona waktu',
    'settings.timezone.description':
      'Digunakan untuk tanggal yang ditampilkan dan impor manual baru.',
    'settings.timezone.system': 'Bawaan sistem',
    'settings.trash.title': 'Masa simpan Sampah',
    'settings.trash.description':
      'Pilih kapan data di Sampah dihapus permanen.',
    'settings.trash.warning':
      'Item yang lebih lama dari periode pilihan dapat dihapus permanen.',
    'settings.trash.updating': 'Memperbarui masa simpan',
    'retention.never': 'Never',
    'retention.30': '30 hari',
    'retention.90': '90 hari',
    'retention.183': '6 bulan',
    'retention.365': '1 tahun',
    'trash.summary': 'Item dihapus permanen setelah {retention}.',
    'trash.summary.never': 'Item tetap di Sampah sampai Anda menghapusnya permanen.',
    'trash.history.empty': 'Riwayat warp yang dihapus disimpan selama {retention}.',
    'trash.accounts.empty': 'Akun yang dihapus disimpan selama {retention}.',
    'trash.backups.empty': 'Cadangan lokal yang dihapus disimpan selama {retention}.',
    'trash.ariaLabel': 'Riwayat Sampah',
    'trash.categories': 'Kategori Sampah',
    'trash.deletedHistory': 'Riwayat terhapus',
    'trash.deletedAccounts': 'Akun terhapus',
    'trash.deletedBackups': 'Cadangan terhapus',
    'trash.tabHistory': 'Riwayat {count}',
    'trash.tabAccounts': 'Akun {count}',
    'trash.tabBackups': 'Cadangan {count}',
    'trash.loading': 'Memuat Sampah',
    'trash.empty': 'Sampah kosong',
    'trash.loadingAccounts': 'Memuat Sampah akun',
    'trash.noAccounts': 'Tidak ada akun terhapus',
    'trash.loadingBackups': 'Memuat Sampah cadangan',
    'trash.noBackups': 'Tidak ada cadangan terhapus',
    'trash.pagination': 'Navigasi halaman Sampah',
    'trash.previousPage': 'Halaman Sampah sebelumnya',
    'trash.nextPage': 'Halaman Sampah berikutnya',
    'trash.restoreSelected': 'Pulihkan yang dipilih ({count})',
    'trash.warpedAt': 'Warp {date}',
    'trash.deletedAt': 'Dihapus {date}',
    'trash.deletingItem': 'Menghapus {item}',
    'trash.permanentlyDeleteItem': 'Hapus permanen {item}',
    'trash.selectBackup': 'Pilih {file}',
    'trash.deletingBackup': 'Menghapus {file}',
    'trash.permanentlyDeleteBackup': 'Hapus permanen {file}',
    'trash.deletingAccount': 'Menghapus UID {uid}',
    'trash.permanentlyDeleteAccount': 'Hapus permanen UID {uid}',
    'roster.title': 'Karakter',
    'roster.reimport': 'Impor ulang',
    'roster.import': 'Impor',
    'roster.importing': 'Mengimpor…',
    'roster.loading': 'Memuat karakter',
    'roster.howToTitle': 'Cara mendapatkan data',
    'roster.howToStep1': 'Buka HoYoLAB dan buka Battle Chronicle untuk Honkai: Star Rail.',
    'roster.howToStep2': 'Buka DevTools (F12) lalu pilih tab Network.',
    'roster.howToStep3': 'Ketik "avatar" di kotak filter dan pilih Fetch/XHR.',
    'roster.howToStep4': 'Klik kanan request "avatar/info", pilih Copy > Copy response.',
    'roster.howToStep5': 'Tempel JSON yang disalin di bawah, lalu klik Impor.',
    'roster.pastePlaceholder': 'Tempel respons JSON di sini…',
    'roster.level': 'Lv.',
    'roster.eidolon': 'Eidolon',
    'roster.lightCone': 'Light Cone',
    'roster.superimpose': 'S{value}',
    'roster.superimposeFull': 'Superimposisi',
    'roster.noLightCone': 'Tanpa Light Cone',
    'roster.searchPlaceholder': 'Cari karakter…',
    'roster.noMatches': 'Tidak ada karakter yang cocok',
  },
} as const

export type MessageKey = keyof (typeof messages)['en']
export type Translator = (
  key: MessageKey,
  values?: Record<string, string | number>,
) => string

export function translate(
  language: AppLanguage,
  key: MessageKey,
  values: Record<string, string | number> = {},
) {
  const template = messages[language][key] ?? messages.en[key]

  return Object.entries(values).reduce(
    (message, [name, value]) =>
      message.replaceAll(`{${name}}`, String(value)),
    template,
  )
}

export function loadLanguagePreference(
  storage: PreferenceStorage | undefined = getBrowserStorage(),
): AppLanguage {
  const value = readPreference(languageStorageKey, storage)

  return value && supportedLanguages.has(value as AppLanguage)
    ? (value as AppLanguage)
    : 'en'
}

export function saveLanguagePreference(
  language: AppLanguage,
  storage: PreferenceStorage | undefined = getBrowserStorage(),
) {
  writePreference(languageStorageKey, language, storage)
}

export function applyLanguagePreference(
  language: AppLanguage,
  root: LanguageRoot | undefined = getDocumentRoot(),
) {
  if (root) {
    root.lang = language
  }
}

export function loadTimeZonePreference(
  storage: PreferenceStorage | undefined = getBrowserStorage(),
): TimeZonePreference {
  const value = readPreference(timeZoneStorageKey, storage)

  return value === 'system' || (value && isValidTimeZone(value))
    ? value
    : 'system'
}

export function saveTimeZonePreference(
  timeZone: TimeZonePreference,
  storage: PreferenceStorage | undefined = getBrowserStorage(),
) {
  if (timeZone === 'system' || isValidTimeZone(timeZone)) {
    writePreference(timeZoneStorageKey, timeZone, storage)
  }
}

export function resolveTimeZone(timeZone: TimeZonePreference) {
  if (timeZone !== 'system') {
    return timeZone
  }

  return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'
}

export function getLocale(language: AppLanguage) {
  return language === 'id' ? 'id-ID' : 'en-US'
}

export function formatRetentionLabel(
  language: AppLanguage,
  retentionDays: number,
) {
  const keyByDays: Record<number, MessageKey> = {
    0: 'retention.never',
    30: 'retention.30',
    90: 'retention.90',
    183: 'retention.183',
    365: 'retention.365',
  }
  const key = keyByDays[retentionDays]

  return key ? translate(language, key) : `${retentionDays} days`
}

function getSupportedTimeZones() {
  const intl = Intl as typeof Intl & {
    supportedValuesOf?: (key: 'timeZone') => string[]
  }

  try {
    return intl.supportedValuesOf?.('timeZone') ?? fallbackTimeZones
  } catch {
    return fallbackTimeZones
  }
}

function isValidTimeZone(value: string) {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: value }).format()
    return true
  } catch {
    return false
  }
}

function readPreference(
  key: string,
  storage: PreferenceStorage | undefined,
) {
  if (!storage) {
    return undefined
  }

  try {
    return storage.getItem(key) ?? undefined
  } catch {
    return undefined
  }
}

function writePreference(
  key: string,
  value: string,
  storage: PreferenceStorage | undefined,
) {
  if (!storage) {
    return
  }

  try {
    storage.setItem(key, value)
  } catch {
    // The preference remains active for the current session.
  }
}

function getBrowserStorage() {
  if (typeof window === 'undefined') {
    return undefined
  }

  try {
    return window.localStorage
  } catch {
    return undefined
  }
}

function getDocumentRoot() {
  return typeof document === 'undefined' ? undefined : document.documentElement
}
